"""
An interface for the c numstore api
"""
from __future__ import annotations

from typing import Any

import numpy as np
import numpy.typing as npt

# Placeholder types for readability 
# and maybe better type support in the future
type nsdb = Any
type nstxn = Any
type nstype = str

# Numstore (string) type to numpy type
def ns_to_np(s: nstype) -> np.dtype: ...

# Open and close a database - return a handle
def db_open(path: str) -> nsdb: ...
def db_close(db: nsdb) -> None: ...

# Transaction control
def db_begin(db: nsdb) -> nstxn: ...
def txn_commit(txn: nstxn) -> None: ...
def txn_rollback(txn: nstxn) -> None: ...

# Variable CRUD
def var_create(db: nsdb, txn: nstxn, var: str, dtype: nstype) -> None: ...
def var_newvar(db: nsdb, txn: nstxn, var: str, data: npt.NDArray) -> None: ...
def var_delete(db: nsdb, txn: nstxn, var: str) -> None: ...
def var_len(db: nsdb, txn: nstxn, var: str) -> int: ...
def var_exists(db: nsdb, txn: nstxn, var: str) -> bool: ...

# Array CRUD
def var_read(db: nsdb, txn: nstxn, var: str, key: range) -> npt.NDArray: ...
def var_insert(db: nsdb, txn: nstxn, var: str, ofst: int, data: npt.NDArray) -> None: ...
def var_write(db: nsdb, txn: nstxn, var: str, key: range, data: npt.NDArray) -> None: ...
def var_remove(db: nsdb, txn: nstxn, var: str, key: range) -> npt.NDArray: ...
